### ISSUE TITLE
Thoughts Crossover from multiple sessions

### ISSUE THREAD

**Issue by ajbarnes** [VT-CHCI/Thought-Swap#13]
Issue found, where, once thoughts have been submitted from one session, even if nothing is done with them though distribute, they can show up in another "new session" when distribute is pressed.

Alternatively, if a teacher refreshes their screen and logs in again while the same server run is going, thoughts from all of their sessions from that run will be visible and will be distribute-able.

Replicate:
- Log on as a teacher and two students, have each student submit 1 thought. Press new session and have each student submit another different thought. Press distribute and confirm that a thought from the first session is showing up in this session.
- Refresh teacher page, log on as same teacher, click on class, confirm that all 4 entered thoughts are there.

**Comment by hcientist** [comment]
this may not be relevant with the refactor
