### ISSUE TITLE
On logout, when a new facilitator logs in they are presented with previous facilitator's groups

### ISSUE THREAD

**Issue by ajbarnes** [VT-CHCI/Thought-Swap#43]
I believe this issue is closely related to the life-cycle of the `GroupMgmtController`, that is it is expected that logout will destroy the controller but it does not, it only changes the path and view. See [this stackoverflow](http://stackoverflow.com/a/16096598/3850442). 

A page refresh corrects the view for the new facilitator but that should never be required.

**Comment by hcientist** [comment]
probably need to delete data (maybe make a funciton for clearing) on userservice and maybe other services (group?)

**Comment by ajbarnes** [comment]
Ended up being fixed once the user service took control of the groups service.
Fixed since 63dbef33cc5814e2a901f8354b6cbeee5083deb1
