### ISSUE TITLE
focus on inputs

### ISSUE THREAD

**Issue by hcientist** [VT-CHCI/Thought-Swap#53]
make it so that pretty much anywhere i need to type starts off with focus

**Comment by ajbarnes** [comment]
Fixed in e9b1ffbaecad8680448adaa24e1ced62cd37e8a4, eb5bb01f3129d33cedf22c1bea119a5d74fcea9e, 052cd069711371751e7c66f9ef7c8bf2ee318b28, and c0a91e183e8c4a71955d3f93c762edfa4a15cf1f
