### ISSUE TITLE
Sockets do not become inactive on window close

### ISSUE THREAD

**Issue by ajbarnes** [VT-CHCI/Thought-Swap#55]
Possible fix by using [`window.onbeforeunload()`](https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onbeforeunload)

**Comment by hcientist** [comment]
are there any steps to reproduce? for now, i'm marking this as fixed in https://github.com/VT-CHCI/Thought-Swap/commit/534849d08b8a38f0b75690483fcc71698a1213f0#diff-2de9eda1655d499e934e7465e87ca0bdR117
