### ISSUE TITLE
Large Screen Adaptability/ Design

### ISSUE THREAD

**Issue by ajbarnes** [VT-CHCI/Thought-Swap#8]
When designing the elements of the app, keep in mind that one of the main uses could be on a projector (teacher uses to show the class thoughts as they are received, maybe)

Will include things like:
-larger text
-images that are acceptable at projector resolution
-etc.

**Comment by hcientist** [comment]
also allow the teacher to reorder the thoughts on their screen

**Comment by ajbarnes** [comment]
Test teacher view at 1024 x 768 resolution
